### ISSUE TITLE
AssetStudio freeze on building tree structure from 2.5.54 .blk files

### ISSUE THREAD

**Issue by Preciel** [Razmoth/GenshinStudio#2] opened 2022-03-18 17:06 UTC
Trying to load from `02636877.blk to 03054574.blk` and from `03057249.blk to 03470968.blk` will freeze AssetStudio while building tree structure and consume tons of RAM. (19Go out of 32Go)

Loading each files individually or by small group of 10 seems to works fine.

Using net6.0-windows.zip.

**Comment by Razmoth** [comment] 2022-03-18 17:13
Greetings.

AssetStudio, by design, loads assets into memory.

Loading multiple files (assuming each has dependencies as well !!), will cause it to consume very large amount of ram.

As for `building tree structure`, not quite sure why does it happen, it happens after 5-7 loading of different files, either GS (Genshin Studio) bug or something that's related to AssetStudio itself.

My advice to load files in bulk is to use the CAB method, it should theoretically have the same output with less ram usage (but more space because it'll extract game assets).

**Comment by Preciel** [comment] 2022-03-18 17:18
Actually, I tried CAB method as it did seems more memory friendly indeed.
But it crash while loading assets at some point.

Just tried to load the same ranges of .blk with the net472.zip build, and this one didn't crash.
So I'm assuming that it's a problem related to .NET 6.0

**Comment by Razmoth** [comment] 2022-03-18 17:22
I see.

It could very well be the case then.

Will need to do more testing across different builds sometime.

Thanks for the feedback.

**Comment by Preciel** [comment] 2022-03-18 21:23
@Razmoth just ahead up on how things went.

Even when loading only 250 .blk files, AssetStudio often crash while building tree structure.
This process is usually fast and simple, not sure why it crash atm...
I have a craft once every two set of files.

**Comment by Razmoth** [comment] 2022-03-22 12:44
@Preciel should be fixed now.

**Comment by Preciel** [comment] 2022-03-22 17:26
Great @Razmoth ! I will give it a go once the new asset studio is compiled and released. ;)

**Closed** 2022-03-22 18:01 UTC
